# Generated by Django 3.2.4 on 2021-06-17 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crittercatcherapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='is_complete',
            field=models.BooleanField(null=True),
        ),
    ]
